<div id="hero">
  <div class="container">
    <div class="row">
	  <h4>FIND YOUR DREAM CAR</h4>
	  <h1>BMW M5 GRAND TURISMO</h1>
	  <h4>
		  MODEL 2017
		  <span>$64,000</span>
	  </h4>
	  <br>
	  <a href="#">SEE DETAILS</a>
	</div>
  </div>
</div>
<div class="hero-1">
  <div class="container-fluid">
    <div class="wrapper-formu">
	  <div class="formu">
	    <form action="register" method="post">
		  <span>select a manufacturer</span>
		  <br>
		  <div class="wrapper-select">
		    <select>
			    <option selected value="Any">Any Make</option>
			    <option value="Alfa">Alfa Romeo</option>
			    <option value="Aston">Aston Martin</option>
			    <option value="Audi">Audi</option>
			    <option value="Bentley">Bentley</option>
			    <option value="BMW">BMW</option>
			    <option value="Bugatti">Bugatti</option>
			  </select>  
		  </div>
		  <br>
		  <span>select a model</span>
		  <br>
		  <div class="wrapper-select">
		    <select>
			    <option selected value="AnyM">Any Model</option>
			    <option value="Model1">Model 1</option>
			    <option value="Model2">Model 2</option>
			    <option value="Model3">Model 3</option>
			    <option value="Model4">Model 4</option>
			    <option value="Model5">Model 5</option>
			    <option value="Model6">Model 6</option>
			  </select>	  
		  </div>
		  <br>
		  <span>select a type</span>
		  <br>
		  <div class="wrapper-select">
		    <select>
			    <option selected value="AnyT">Any Tipe</option>
			    <option value="Type1">Type 1</option>
			    <option value="Type2">Type 2</option>
			    <option value="Type3">Type 3</option>
			    <option value="Type4">Type 4</option>
			    <option value="Type5">Type 5</option>
			    <option value="Type6">Type 6</option>
			  </select>
		  </div>
		  <br>
		  <span>price range</span>
		  <div class="wrapper-slide">
		    
		  </div>
		  <hr>
		  <button type="submit">submit filters ></button>
		  <br>
		  <a href="#">reset all filters</a>
	    </form>  
	  </div>
    </div>
  </div>
</div>