<div id="car-list">
  <div class="back-home">
    <a href="../welcome/welcome.inc">Home</a>
    <p>> Search Results</p>
  </div>
  <div class="container">
    <div class="row">
      <div class="cars col-xs-12 col-sm-12 col-md-9">
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
        <div class="seg">
          <div class="car-image col-xs-12 col-sm-6">
            <img src="../images/car-listing/audi-s.jpg"/>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="seg-header">
              <div class="title">
                <h3>Audi S Coupe</h3>
                <div class="subtitle">
                  <div class="paragraph">
                    <p>First dive review</p>
                  </div>
                  <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                </div>
              </div>
                  <p class="price">$99,415</p>
            </div><!--seg-header-->
            <div class="hr">
              <hr>
            </div>
            <div class="car-paragraph">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div><!--car-paragraph-->
  
            <div class="car-data">
              <div class="data">
                <div class="kilometer">
                  <div class="road-icon">
                    <i class="fas fa-road"></i>
                  </div>
                  <div class="mileage">
                    <p>0 kM</p>
                  </div> 
                </div>
                <div class="car-details">
                  <a href="#">Registered 2017 /</a>
                  <a href="#">New /</a>
                  <a href="#">8-Speed Automatic /</a>
                  <a href="#">Petrol</a>
                </div>
              </div><!--data-->
              <div class="cta-details">
                <input type="button" class="btn btn-default" value="View details >"/>
              </div>
            </div><!--car-data-->
          </div>

          
        </div><!--seg-->
      </div><!--cars-->
    </div><!--row-->
  </div><!--container-->
</div><!--car-list-->
