<div id="filter-bar">
  <div class="container">
    <div class="row">
      <div class="column col-xs-12 col-sm-6">
          <div class="seg">
      <div class="paragraph">
        <p>Select a manufacturer</p>
      </div>
      <div class="sort-button">
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Any Make
            <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <li><a href="#">Alfa Romeo</a></li>
            <li><a href="#">Aston Martin</a></li>
            <li><a href="#">Bentley</a></li>
            <li><a href="#">BMW</a></li>
            <li><a href="#">Bugatti</a></li>
          </ul>
        </div>
      </div>
    </div>
          <div class="seg">
            <div class="paragraph">
              <p>Select a model</p>
            </div>
            <div class="sort-button">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Any Model
                  <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="#">Model 1</a></li>
                  <li><a href="#">Model 2</a></li>
                  <li><a href="#">Model 3</a></li>
                  <li><a href="#">Model 4</a></li>
                  <li><a href="#">Model 5</a></li>
                  <li><a href="#">Model 6</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="seg">
            <div class="paragraph">
              <p>Select a type</p>
            </div>
            <div class="sort-button">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Any Type
                  <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="#">Type 1</a></li>
                  <li><a href="#">Type 2</a></li>
                  <li><a href="#">Type 3</a></li>
                  <li><a href="#">Type 4</a></li>
                  <li><a href="#">Type 5</a></li>
                  <li><a href="#">Type 6</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="seg">
            <div class="paragraph">
              <p>Select a status</p>
            </div>
            <div class="sort-button">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Any Status
                  <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="#">Status 1</a></li>
                  <li><a href="#">Status 2</a></li>
                  <li><a href="#">Status 3</a></li>
                  <li><a href="#">Status 4</a></li>
                  <li><a href="#">Status 5</a></li>
                  <li><a href="#">Status 6</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="seg">
            <div class="paragraph">
              <p>Select a min year</p>
            </div>
            <div class="sort-button">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Any Year
                  <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="#">2018</a></li>
                  <li><a href="#">2017</a></li>
                  <li><a href="#">2016</a></li>
                  <li><a href="#">2015</a></li>
                  <li><a href="#">2014</a></li>
                  <li><a href="#">2013</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="seg">
            <div class="paragraph">
              <p>Select a max year</p>
            </div>
            <div class="sort-button">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Any Year
                  <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="#">2018</a></li>
                  <li><a href="#">2017</a></li>
                  <li><a href="#">2016</a></li>
                  <li><a href="#">2015</a></li>
                  <li><a href="#">2014</a></li>
                  <li><a href="#">2013</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="slider">
            aquí va el slider
          </div>
          <div class="hr">
            <hr>
          </div>
          <div class="cta-submit">
            <input type="button" class="btn btn-default" value="Submit filters >"/>
            <div class="reset">
              <a href="#">Reset all filters</a>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
