<div id="view-bar">
  <div class="container">
    <div class="row">
      <div class="select col-xs-8 pull-right col-sm-5">
        <div class="view-wrapper">
          <p>
            Select view
          </p>
          <div class="buttons">
            <div class="list-button">
              <i class="fas fa-list"></i>
            </div>
            <div class="grid-button">
              <i class="fas fa-th"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="sort col-xs-8 pull-right col-sm-5">
        <div class="sort-wrapper">
          <p>
            Sort by
          </p>
          <div class="sort-button">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Last Added
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><a href="#">Last Added</a></li>
                <li><a href="#">Popular</a></li>
                <li><a href="#">Price</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
