<div id="best-offers">
  <div class="container-fluid">

    <div class="row">
      <div class="col-12">
        <div class="title">
          <h1>BEST OFFERS FROM AUTOCLUB</h1>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="most-researched float-right">
          <a href="#">MOST RESEARCHED MANUFACTURERS</a>
        </div>
      </div>
      <div class="col-12 col-md-6 float-left">
        <div class="latest-vehicles">
          <a href="#">LATEST VEHICLES ON SALE</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-3">
        <div class="models">
          <ul class="category">
            <li><a href="">ALL MANUFACTURERS</a><span>></span></li>
            <li><a href="">ASTON MARTIN</a><span>></span></li>
            <li><a href="">ALPHA ROMEO</a><span>></span></li>
            <li><a href="">AUDI</a><span>></span></li>
            <li><a href="">BMW</a><span>></span></li>
            <li><a href="">LAND ROVER</a><span>></span></li>
            <li><a href="">MERCEDES-BENZ</a><span>></span></li>
            <li><a href="">PORSHE</a><span>></span></li>
            <li><a href="">SUZUKI</a><span>></span></li>
            <li><a href="">TOYOTA</a><span>></span></li>
            <li><a href="">VOLVO</a><span>></span></li>
            <li><a href="">VOLKSWAGWEN</a><span>></span></li>
          </ul>
        </div>
      </div>

      <div class="col-12 col-md-9">
        <div class="row">
          <div class="col-12 col-sm-6 col-lg-4">
            <img src="images/home-7-270x150.jpg" class="img-fluid" alt="Responsive image">
            <div class="content">
              <div class="registered">
                <p>REGISTERED 2017</p>
              </div>
              <div class="name-of-vehicle">
                <h4>2017 Lexus-AMG C63</h4>
              </div>
              <div class="info">
                <span class="price">31,900</span>
                <span class="distance">12,000 KM</span>
              </div>
              <div class="model">
                <ul class="nav">
                  <li><a href="#">Used</a></li>
                  <li><a href="#">2015</a></li>
                  <li><a href="#">Automatic</a></li>
                  <li><a href="#">Red</a></li>
                  <li><a href="#">Petrol</a></li>
                </ul>
              </div>
            </div>
          </div>

        <div class="col-12 col-sm-6 col-lg-4">
          <img src="images/home-4-270x150.jpg">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2015</p>
            </div>
            <div class="name-of-vehicle">
              <h4>BMW M6 Sport hybrid</h4>
            </div>
            <div class="info">
              <span class="price">24,380</span>
              <span class="distance">35,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">White</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-lg-4">
          <img src="images/home-5-270x150.jpg">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2016</p>
            </div>
            <div class="name-of-vehicle">
              <h4>2016 Ferrari Testarosa</h4>
            </div>
            <div class="info">
              <span class="price">95,900</span>
              <span class="distance">99,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Red</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-lg-4">
          <img src="images/home-6-270x150.jpg">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2015</p>
            </div>
            <div class="name-of-vehicle">
              <h4>2016 Bugatti Veyron</h4>
            </div>
            <div class="info">
              <span class="price">98,995</span>
              <span class="distance">95,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Blue</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-lg-4">
          <img src="images/home-8-270x150.jpg">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2016</p>
            </div>
            <div class="name-of-vehicle">
              <h4>Mercedes - AMG</h4>
            </div>
            <div class="info">
              <span class="price">19,995</span>
              <span class="distance">52,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Yellow</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-lg-4">
          <img src="images/home-9-270x150.jpg">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2017</p>
            </div>
            <div class="name-of-vehicle">
              <h4>2017 Mercedes - AMG</h4>
            </div>
            <div class="info">
              <span class="price">64,308</span>
              <span class="distance">210 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Black</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
