<div id="best-offers">
  <div class="container-fluid">

    <div class="search-vehicles">
      <a href="">MOST RESEARCHED MANUFACTURERS</a>
      <a href="">LATEST VEHICLES ON SALE</a>
    </div>

    <div class="row">
      <div class="col-12 col-md-3">
        <div class="models">
          <ul class="category">
            <li><a href="">ALL MANUFACTURERS</a></li>
            <li><a href="">ASTON MARTIN</a></li>
            <li><a href="">ALPHA ROMEO</a></li>
            <li><a href="">AUDI</a></li>
            <li><a href="">BMW</a></li>
            <li><a href="">LAND ROVER</a></li>
            <li><a href="">MERCEDES-BENZ</a></li>
            <li><a href="">PORSHE</a></li>
            <li><a href="">SUZUKI</a></li>
            <li><a href="">TOYOTA</a></li>
            <li><a href="">VOLVO</a></li>
            <li><a href="">VOLKSWAGWEN</a></li>
          </ul>
        </div>
      </div>

      <div class="col-12 col-md-9">
        <div class="row">
          <div class="col-12 col-xxs-6 col-sm-4 col-lg-4">
            <img src="images/home-7-270x150.jpg" class="img-fluid img" alt="Responsive image">
            <div class="content">
              <div class="registered">
                <p>REGISTERED 2017</p>
              </div>
              <div class="name-of-vehicle">
                <h4><a href="">2017 Lexus-AMG C63</a></h4>
              </div>
              <div class="info">
                <span class="price"><i class="fas fa-dollar-sign"></i><i class="color">31,900</i></span>
                <span class="distance"><i class="fas fa-road right"></i>12,000 KM</span>
              </div>
              <div class="model">
                <ul class="nav">
                  <li><a href="#">Used</a></li>
                  <li><a href="#">2015</a></li>
                  <li><a href="#">Automatic</a></li>
                  <li><a href="#">Red</a></li>
                  <li><a href="#">Petrol</a></li>
                </ul>
              </div>
            </div>
          </div>

        <div class="col-12 col-xxs-6 col-sm-4 col-lg-4">
          <img src="images/home-4-270x150.jpg" class="img-fluid img" alt="Responsive image">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2015</p>
            </div>
            <div class="name-of-vehicle">
              <h4><a href="">BMW M6 Sport hybrid</a></h4>
            </div>
            <div class="info">
              <span class="price"><i class="fas fa-dollar-sign"></i><i class="color">24,380</i></span>
              <span class="distance"><i class="fas fa-road"></i>35,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">White</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-xxs-6 col-sm-4 col-lg-4">
          <img src="images/home-5-270x150.jpg" class="img-fluid img" alt="Responsive image">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2016</p>
            </div>
            <div class="name-of-vehicle">
              <h4><a href="">2016 Ferrari Testarosa</a></h4>
            </div>
            <div class="info">
              <span class="price"><i class="fas fa-dollar-sign"></i><i class="color">95,900</i></span>
              <span class="distance"><i class="fas fa-road"></i>99,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Red</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-xxs-6 col-sm-4 col-lg-4">
          <img src="images/home-6-270x150.jpg" class="img-fluid img" alt="Responsive image">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2015</p>
            </div>
            <div class="name-of-vehicle">
              <h4><a href="">2016 Bugatti Veyron</a></h4>
            </div>
            <div class="info">
              <span class="price"><i class="fas fa-dollar-sign"></i><i class="color">98,995</i></span>
              <span class="distance"><i class="fas fa-road"></i>95,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Blue</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-xxs-6 col-sm-4 col-lg-4">
          <img src="images/home-8-270x150.jpg" class="img-fluid img" alt="Responsive image">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2016</p>
            </div>
            <div class="name-of-vehicle">
              <h4><a href="">Mercedes - AMG</a></h4>
            </div>
            <div class="info">
              <span class="price"><i class="fas fa-dollar-sign"></i><i class="color">19,995</i></span>
              <span class="distance"><i class="fas fa-road"></i>52,000 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Yellow</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-12 col-xxs-6 col-sm-4 col-lg-4">
          <img src="images/home-9-270x150.jpg" class="img-fluid img" alt="Responsive image">
          <div class="content">
            <div class="registered">
              <p>REGISTERED 2017</p>
            </div>
            <div class="name-of-vehicle">
              <h4><a href="">2017 Mercedes - AMG</a></h4>
            </div>
            <div class="info">
              <span class="price"><i class="fas fa-dollar-sign"></i><i class="color">64,308</i></span>
              <span class="distance"><i class="fas fa-road"></i>210 KM</span>
            </div>
            <div class="model">
              <ul class="nav">
                <li><a href="#">Used</a></li>
                <li><a href="#">2015</a></li>
                <li><a href="#">Automatic</a></li>
                <li><a href="#">Black</a></li>
                <li><a href="#">Petrol</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
