<div id="best-offers">
  <div class="container-fluid">

    <div class="row">
      <div class="col-12">
        <div class="title">
          <h1>BEST OFFERS FROM AUTOCLUB</h1>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="most-researched float-right">
          <a href="#">MOST RESEARCHED MANUFACTURERS</a>
        </div>
      </div>
      <div class="col-12 col-md-6 float-left">
        <div class="latest-vehicles">
          <a href="#">LATEST VEHICLES ON SALE</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-sm-6 col-lg-4">
        <img src="images/home-7-270x150.jpg">
        <div class="content">
          <div class="registered">
            <p>REGISTERED 2017</p>
          </div>
          <div class="name-of-vehicle">
            <h1>2017 Lexus-AMG C63</h1>
          </div>
          <div class="price">
            <p>31,900</p>
          </div>
          <div class="distance">
            <p>12,000 KM</p>
          </div>
          <div class="model">
            <ul class="nav">
              <li><a href="#">Used</a></li>
              <li><a href="#">2015</a></li>
              <li><a href="#">Automatic</a></li>
              <li><a href="#">Red</a></li>
              <li><a href="#">Petrol</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-4">
        <img src="images/home-4-270x150.jpg">
        <div class="content">
          <div class="registered">
            <p>REGISTERED 2015</p>
          </div>
          <div class="name-of-vehicle">
            <h1>BMW M6 Sport hybrid</h1>
          </div>
          <div class="price">
            <p>24,380</p>
          </div>
          <div class="distance">
            <p>35,000 KM</p>
          </div>
          <div class="model">
            <ul class="nav">
              <li><a href="#">Used</a></li>
              <li><a href="#">2015</a></li>
              <li><a href="#">Automatic</a></li>
              <li><a href="#">White</a></li>
              <li><a href="#">Petrol</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-4">
        <img src="images/home-5-270x150.jpg">
        <div class="content">
          <div class="registered">
            <p>REGISTERED 2016</p>
          </div>
          <div class="name-of-vehicle">
            <h1>2016 Ferrari Testarosa</h1>
          </div>
          <div class="price">
            <p>95,900</p>
          </div>
          <div class="distance">
            <p>99,000 KM</p>
          </div>
          <div class="model">
            <ul class="nav">
              <li><a href="#">Used</a></li>
              <li><a href="#">2015</a></li>
              <li><a href="#">Automatic</a></li>
              <li><a href="#">Red</a></li>
              <li><a href="#">Petrol</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-4">
        <img src="images/home-6-270x150.jpg">
        <div class="content">
          <div class="registered">
            <p>REGISTERED 2015</p>
          </div>
          <div class="name-of-vehicle">
            <h1>2016 Bugatti Veyron</h1>
          </div>
          <div class="price">
            <p>98,995</p>
          </div>
          <div class="distance">
            <p>95,000 KM</p>
          </div>
          <div class="model">
            <ul class="nav">
              <li><a href="#">Used</a></li>
              <li><a href="#">2015</a></li>
              <li><a href="#">Automatic</a></li>
              <li><a href="#">Blue</a></li>
              <li><a href="#">Petrol</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-4">
        <img src="images/home-8-270x150.jpg">
        <div class="content">
          <div class="registered">
            <p>REGISTERED 2016</p>
          </div>
          <div class="name-of-vehicle">
            <h1>Mercedes - AMG</h1>
          </div>
          <div class="price">
            <p>19,995</p>
          </div>
          <div class="distance">
            <p>52,000 KM</p>
          </div>
          <div class="model">
            <ul class="nav">
              <li><a href="#">Used</a></li>
              <li><a href="#">2015</a></li>
              <li><a href="#">Automatic</a></li>
              <li><a href="#">Yellow</a></li>
              <li><a href="#">Petrol</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-4">
        <img src="images/home-9-270x150.jpg">
        <div class="content">
          <div class="registered">
            <p>REGISTERED 2017</p>
          </div>
          <div class="name-of-vehicle">
            <h1>2017 Mercedes - AMG</h1>
          </div>
          <div class="price">
            <p>64,308</p>
          </div>
          <div class="distance">
            <p>210 KM</p>
          </div>
          <div class="model">
            <ul class="nav">
              <li><a href="#">Used</a></li>
              <li><a href="#">2015</a></li>
              <li><a href="#">Automatic</a></li>
              <li><a href="#">Black</a></li>
              <li><a href="#">Petrol</a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
