<div class="choose-us container-fluid">

  <div class="text row">

    <h5>WORLD'S LEADING CAR DEALER</h5>
    <hr align="left" class="hrleft">
    <hr align="center" class="hrcenter">
    <h3>WHY PEOPLE CHOOSE US</h3>

    <div class="paragraph1 col-md-6">
      <p>As a local, family-owned dealership, we understand the needs of our customers, and we give back to our local community. We also offer great benefits to all our customers, both new & returning. Feel free to check more reasons for becoming our client and having a hassle-free buying experience.</p>
    </div>

    <div class="list1 col-md-6">
      <ul>
        <li>A wide range of affordable vehicles for everyone</li>
        <li>Certified vehicles of various types and sizes</li>
        <li>Lots of additional products and accessories</li>
        <li>Competitive freight options available to every client</li>
      </ul>
    </div>
  </div>
</div>

<div class="numbers container-fluid">

  <div class="row">

    <div class="col-sm-6 col-md-3">
      <div class="icon-numbers">
        <i class="fas fa-car-alt"></i>
      </div>

      <div class="text-numbers">
        <h3>1250</h3>
        <p>NEW CARS IN STOCK</p>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="icon-numbers">
        <i class="fas fa-car-crash"></i>
      </div>

      <div class="text-numbers">
        <h3>2120+</h3>
        <p>USED CARS IN STOCK</p>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="icon-numbers">
        <i class="fas fa-smile"></i>
      </div>

      <div class="text-numbers">
        <h3>9753</h3>
        <p>HAPPY COSTUMERS</p>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="icon-numbers">
        <i class="fas fa-tools"></i>
      </div>

      <div class="text-numbers">
        <h3>1022</h3>
        <p>CAR SPARE PARTS</p>
      </div>
    </div>
  </div>
</div>
