<div id="welcome">
  <div class="container">
      <div class="row">

          <div class="col">
            <div class="img">
              <img src="../../../images/logo-white.png">
            </div>
          </div>

          <div class="col">
            <div class="welcome-to-our-website">

                <div class="title">

                  <h1>
                    WELCOME TO OUR WEBSITE
                  </h1>

                </div>

                <div class="line">
                  
                </div>

            </div>
          </div>

          <div class="col">
            <div class="the-first">

              <h1>
                #1 PLACE FOR ALL YOUR AUTOMOTIVE NEEDS
              </h1>

            </div>
          </div>

          <div class="col">
            <div class="body">

              <p>
                Autozone is a leading digital automotive marketplace designed to connect vehicle buyers and sellers. Our website lets you research and compare new, certified and used cars by searching for body type, mileage, price and numerous other criteria.
              </p>

            </div>
          </div>

      </div>
  </div>
</div>
