<div id="header-mobile" class="Fixed">
  <a href="#" id="menu-button"><img src="images/logo.png" class="img-logo"></img></a>
</div>

<div id="header">
  <nav id="my-menu">
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Pages</a>
         <ul class="Vertical">
            <li><a href="#"><dir>CAR LISTING (RIGHT SIDEBAR)</dir></a></li>
            <li><a href="#"><dir>CAR LISTING (LEFT SIDEBAR)</dir></a></li>
            <li><a href="#"><dir>CAR LISTING (WITHOUT SHADOW)</dir></a></li>
            <li><a href="#"><dir>CAR DETAILS (RIGHT SIDEBAR)</dir></a></li>
            <li><a href="#"><dir>CAR DETAILS (LEFT SIDEBAR)</dir></a></li>
         </ul>
      </li>
      <li><a href="#">About</a></li>
      <li><a href="#">Best Offers</a></li>
      <li><a href="#">Testimonials</a></li>
      <li><a href="#">Contacts</a></li>
    </ul>
  </nav>
</div>

<div id="header-desktop">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="logo">
          <a href="#"><img src="images/logo.png" class="img-responsive"></a>
        </div>
      </div>
      <div class="col-sm-1">
        <a href="#">HOME</a>
      </div>
      <div class="col-sm-1">
        <a href="#">PAGES</a>
      </div>
      <div class="col-sm-1">
        <a href="#">ABOUT</a>
      </div>
      <div class="col-sm-2">
        <a href="#">BEST OFFERS</a>
      </div>
      <div class="col-sm-2">
        <a href="#">TESTIMONIALS</a>
      </div>
      <div class="col-sm-1">
        <a href="#">CONTACTS</a>
      </div>
    </div>
  </div>
</div>
