<div id="three-columns">
  <div class="wrapper-three-columns">
    <div class="mustang col-xs-12 col-sm-4 space">
      <div class="image">
        <img src="../images/mustang.jpg">
      </div>
      <span>FIRST DRIVE REVIEW</span>
      <h4>2010 Ford Mustang/YELLOW</h4>
      <hr>
      <p>The 2010 Ford Mustang beats its competitors with top safety scores and a large trunk. A redesigned cabin also helps the Mustang stand out in its class.</p>
      <a href="#">READ MORE</a>
    </div>
    <div class="bugatti col-xs-12 col-sm-4 space">
      <div class="image">
        <img src="../images/bugatti.jpg">
      </div>
      <span>INSTRUMENTED TEST</span>
      <h4>1950 Bugatti/BLACK</h4>
      <hr>
      <p>The Type 101 was presented at the 1951 Paris Salon, of which two examples were shown. These were a convertible and a coupe, both bodied by Gangloff.</p>
      <a href="#">READ MORE</a>
    </div>
    <div class="mercedes col-xs-12 col-sm-4 space">
      <div class="image">
        <img src="../images/mercedes.jpg">
      </div>
      <span>BUYERS INFO</span>
      <h4>2013 Mercedes C/WHITE</h4>
      <hr>
      <p>The base 2013 Mercedes C250 is powered by a turbocharged four-cylinder engine that has enough acceleration to make highway passing maneuvers easy.</p>
      <a href="#">READ MORE</a>
    </div>
  </div>
</div>
