<div id="three-columns">
  <div class="row">
    <div class="wrapper-three-columns">
      <div class="mustang col-sm-4">
        <img src="../images/mustang.jpg">
        <span>FIRST DRIVE REVIEW</span>
        <h6>2010 Ford Mustang/YELLOW</h6>
        <hr>
        <p>The 2010 Ford Mustang beats its competitors with top safety scores and a large trunk. A redesigned cabin also helps the Mustang stand out in its class.</p>
        <a href="#">READ MORE</a>
      </div>
      <div class="bugatti col-sm-4">
        <img src="../images/bugatti.jpg">
        <span>INSTRUMENTED TEST</span>
        <h6>1950 Bugatti/BLACK</h6>
        <hr>
        <p>The Type 101 was presented at the 1951 Paris Salon, of which two examples were shown. These were a convertible and a coupe, both bodied by Gangloff.</p>
        <a href="#">READ MORE</a>
      </div>
      <div class="mercedes col-sm-4">
        <img src="../images/mercedes.jpg">
        <span>BUYERS INFO</span>
        <h6>2013 Mercedes C/WHITE</h6>
        <hr>
        <p>The base 2013 Mercedes C250 is powered by a turbocharged four-cylinder engine that has enough acceleration to make highway passing maneuvers easy.</p>
        <a href="#">READ MORE</a>
      </div>
    </div>
  </div>
</div>
