<div id="autozone">
  <div class="container">
    <div class="row">
      <div class="auto">
        <h6>Autozone</h6>
        <p>202 W 7th St, Suite 233 Los Angeles, CA 90014 USA</p>
        <a href="#">info@demolink.org</a>
        <a href="#">1-800-624-5462</a>
        <p>Monday to Friday from 09.00 to 18.00</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="formulary">
        <form action="register.php" method="post">
          <input type="text" value="Full name">
          <input type="text" value="E-mail address">
          <textarea rows="60" cols="10">Message</textarea>
          <button type="SEND MESSAGE"></button>
        </form>
      </div>
    </div>
  </div>
</div>
